In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.5],
               [4, 5, 6]])

In [5]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6. ]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a2.shape

(2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

In [16]:
pd.DataFrame(a2)

0    1    2
0  1.0  2.0  3.5
1  4.0  5.0  6.0

In [17]:
len(a2)

2

In [18]:
len(a1)

3

In [19]:
len(a3)

2

## Create Numpy Arrays

In [20]:
ones = np.ones((3,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.size

9

In [23]:
ones.shape

(3, 3)

In [24]:
ones.dtype

dtype('float64')

In [25]:
zeros = np.zeros((3,3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
zeros.size

9

In [28]:
zeros.shape

(3, 3)

In [29]:
zeros.ndim

2

In [30]:
ra = np.arange(0, 10, 2)
ra

array([0, 2, 4, 6, 8])

In [31]:
ra.size

5

In [32]:
ra.shape

(5,)

In [33]:
ra1 = np.random.randint(0, 10, size=(5,5))
ra1

array([[7, 8, 7, 5, 1],
       [4, 7, 3, 2, 3],
       [4, 3, 2, 2, 0],
       [1, 4, 0, 7, 5],
       [9, 9, 7, 1, 7]])

In [34]:
ra1.shape

(5, 5)

In [35]:
ra1.size

25

In [36]:
ra1.ndim

2

In [37]:
ra2 = np.random.random((3, 4))
ra2

array([[0.5647537 , 0.05242289, 0.03719687, 0.34148617],
       [0.78678128, 0.88618968, 0.90259099, 0.95717355],
       [0.8600322 , 0.75569267, 0.95822248, 0.76057522]])

In [38]:
ra2.ndim

2

In [39]:
ra2.shape

(3, 4)

In [40]:
ra2.size

12

In [41]:
ra2.dtype

dtype('float64')

In [42]:
ra3 = np.random.rand(1,2,3,4)

In [43]:
ra3

array([[[[0.62291134, 0.39554192, 0.55002978, 0.31392594],
         [0.26267242, 0.89705229, 0.27667196, 0.22595463],
         [0.26080788, 0.532879  , 0.47095738, 0.45921442]],

        [[0.73790533, 0.78602333, 0.8117252 , 0.57602171],
         [0.13882474, 0.517497  , 0.69989427, 0.85788195],
         [0.67319481, 0.51803219, 0.68746702, 0.75641779]]]])

In [44]:
ra3.shape

(1, 2, 3, 4)

In [45]:
ra3.size

24

In [46]:
ra3.ndim

4

In [47]:
ra3.dtype

dtype('float64')

## Experimenting with random seed

In [48]:
np.random.seed(seed=3)
np.random.randint(10, size=(2,2))

array([[8, 9],
       [3, 8]])

In [49]:
np.random.seed(3)
np.random.randint(10)

8

## Viewing Arrays

In [50]:
np.unique(ra1)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [51]:
a1

array([1, 2, 3])

In [52]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6. ]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [54]:
a1[0]

1

In [55]:
a2[0]

array([1. , 2. , 3.5])

In [56]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a3[:4]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [60]:
q = [1,2,3,4]

In [61]:
q[:2]

[1, 2]

In [65]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[9, 3, 8, 8, 0],
         [5, 3, 9, 9, 5],
         [7, 6, 0, 4, 7],
         [8, 1, 6, 2, 2]],

        [[1, 3, 5, 8, 1],
         [8, 7, 8, 1, 0],
         [5, 4, 1, 5, 4],
         [7, 6, 0, 0, 9]],

        [[2, 4, 5, 8, 8],
         [7, 5, 1, 1, 1],
         [5, 5, 7, 4, 3],
         [0, 0, 0, 0, 2]]],


       [[[2, 7, 0, 5, 0],
         [1, 4, 1, 2, 2],
         [4, 8, 0, 6, 0],
         [4, 1, 5, 1, 8]],

        [[8, 7, 0, 0, 9],
         [1, 7, 8, 7, 4],
         [0, 0, 4, 3, 0],
         [8, 2, 7, 2, 1]],

        [[3, 2, 4, 1, 2],
         [2, 7, 3, 4, 1],
         [6, 7, 9, 1, 0],
         [0, 5, 8, 4, 8]]]])

In [66]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [71]:
a4[:, :, :, :]

array([[[[9, 3, 8, 8, 0],
         [5, 3, 9, 9, 5],
         [7, 6, 0, 4, 7],
         [8, 1, 6, 2, 2]],

        [[1, 3, 5, 8, 1],
         [8, 7, 8, 1, 0],
         [5, 4, 1, 5, 4],
         [7, 6, 0, 0, 9]],

        [[2, 4, 5, 8, 8],
         [7, 5, 1, 1, 1],
         [5, 5, 7, 4, 3],
         [0, 0, 0, 0, 2]]],


       [[[2, 7, 0, 5, 0],
         [1, 4, 1, 2, 2],
         [4, 8, 0, 6, 0],
         [4, 1, 5, 1, 8]],

        [[8, 7, 0, 0, 9],
         [1, 7, 8, 7, 4],
         [0, 0, 4, 3, 0],
         [8, 2, 7, 2, 1]],

        [[3, 2, 4, 1, 2],
         [2, 7, 3, 4, 1],
         [6, 7, 9, 1, 0],
         [0, 5, 8, 4, 8]]]])

## Manipulating and Comparing Arrays

In [72]:
a1

array([1, 2, 3])

In [73]:
ones = np.ones(3)

In [74]:
ones

array([1., 1., 1.])

In [75]:
a1+ones

array([2., 3., 4.])

In [76]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6. ]])

In [77]:
a1 + a2

array([[2. , 4. , 6.5],
       [5. , 7. , 9. ]])

In [78]:
a1/a2

array([[1.        , 1.        , 0.85714286],
       [0.25      , 0.4       , 0.5       ]])

In [79]:
np.divide(a1, a2)

array([[1.        , 1.        , 0.85714286],
       [0.25      , 0.4       , 0.5       ]])

In [80]:
np.divmod(a1, a2)

(array([[1., 1., 0.],
        [0., 0., 0.]]),
 array([[0., 0., 3.],
        [1., 2., 3.]]))

In [81]:
a1 + a3

array([[[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]],

       [[11, 13, 15],
        [14, 16, 18],
        [17, 19, 21]]])

In [82]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [91]:
np.reshape(a2, (2, 1, 3)) + a3

array([[[ 2. ,  4. ,  6.5],
        [ 5. ,  7. ,  9.5],
        [ 8. , 10. , 12.5]],

       [[14. , 16. , 18. ],
        [17. , 19. , 21. ],
        [20. , 22. , 24. ]]])