In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.5],
               [4, 5, 6]])

In [5]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.5],
       [4. , 5. , 6. ]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a2.shape

(2, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

In [16]:
pd.DataFrame(a2)

0    1    2
0  1.0  2.0  3.5
1  4.0  5.0  6.0

In [17]:
len(a2)

2

In [18]:
len(a1)

3

In [19]:
len(a3)

2

## Create Numpy Arrays

In [20]:
ones = np.ones((3,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.size

9

In [23]:
ones.shape

(3, 3)

In [24]:
ones.dtype

dtype('float64')

In [25]:
zeros = np.zeros((3,3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
zeros.size

9

In [28]:
zeros.shape

(3, 3)

In [29]:
zeros.ndim

2

In [30]:
ra = np.arange(0, 10, 2)
ra

array([0, 2, 4, 6, 8])

In [31]:
ra.size

5

In [32]:
ra.shape

(5,)

In [33]:
ra1 = np.random.randint(0, 10, size=(5,5))
ra1

array([[9, 8, 0, 6, 4],
       [2, 6, 1, 9, 7],
       [3, 1, 1, 1, 9],
       [9, 4, 4, 9, 6],
       [2, 5, 7, 7, 5]])

In [34]:
ra1.shape

(5, 5)

In [35]:
ra1.size

25

In [38]:
ra1.ndim

2

In [39]:
ra2 = np.random.random((3, 4))
ra2

array([[0.11108076, 0.33248535, 0.35096918, 0.55613694],
       [0.3905031 , 0.84204396, 0.80407708, 0.93432626],
       [0.86592762, 0.22950926, 0.03425023, 0.29872455]])

In [40]:
ra2.ndim

2

In [41]:
ra2.shape

(3, 4)

In [42]:
ra2.size

12

In [43]:
ra2.dtype

dtype('float64')

In [44]:
ra3 = np.random.rand(1,2,3,4)

In [45]:
ra3

array([[[[0.29499817, 0.71002206, 0.24889473, 0.50278712],
         [0.38296488, 0.01095199, 0.52213268, 0.30665959],
         [0.85106985, 0.81976982, 0.08683472, 0.70444976]],

        [[0.95604928, 0.48002016, 0.24820489, 0.42764744],
         [0.39887668, 0.09061701, 0.8316041 , 0.99106798],
         [0.52976369, 0.71749074, 0.40060672, 0.80424973]]]])

In [46]:
ra3.shape

(1, 2, 3, 4)

In [47]:
ra3.size

24

In [48]:
ra3.ndim

4

In [49]:
ra3.dtype

dtype('float64')

## Experimenting with random seed

In [125]:
np.random.seed(seed=3)
np.random.randint(10, size=(2,2))

array([[8, 9],
       [3, 8]])

In [132]:
np.random.seed(3)
np.random.randint(10)

8