# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3]],
              [[4, 5, 6]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.size, a1.ndim, a1.dtype

((3,), 3, 1, dtype('int64'))

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.size, a2.ndim, a2.dtype

((2, 3), 6, 2, dtype('int64'))

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.size, a3.ndim, a3.dtype

((2, 1, 3), 6, 3, dtype('int64'))

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df1 = pd.DataFrame(a2)
df1

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
r1 = np.random.randint(10, size=(7,2))
r1

array([[4, 3],
       [0, 8],
       [2, 5],
       [3, 5],
       [7, 0],
       [2, 5],
       [6, 3]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
r2 = np.random.random(size=(3,5))
r2

array([[0.11333891, 0.64367038, 0.07273731, 0.82608259, 0.32916263],
       [0.28358165, 0.78615074, 0.05972857, 0.8119106 , 0.53617672],
       [0.43245145, 0.18577686, 0.31333074, 0.39818182, 0.02250358]])

In [22]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
r3 = np.random.randint(10, size=(4,6))
r3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
r4 = np.random.randint(1, 10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(r4)

array([1, 2, 3, 4, 5, 7, 9])

In [25]:
r4

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [24]:
# Find the 0'th index of the latest array you created
r4[0]

array([9, 1, 3, 7, 4, 9, 3])

In [26]:
# Get the first 2 rows of latest array you created
r4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array
r4[:2, :2]

array([[9, 1],
       [5, 3]])

In [29]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
r5 = np.random.randint(10, size=(3,5))
ones2 = np.ones((3,5))

In [30]:
r5

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [31]:
ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# Add the two arrays together
r5 + ones2

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [33]:
# Create another array of ones of shape (5, 3)
ones3 = np.ones((5,3))
ones3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Try add the array of ones and the other most recent array together
r5 + ones3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [36]:
r5 + ones3.reshape((3, 5))

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [35]:
# Create another array of ones of shape (3, 5)
ones4 = np.ones((3,5))
ones4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
# Subtract the new array of ones from the other most recent array
r5 - ones4

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [39]:
r5

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [38]:
# Multiply the ones array with the latest array
r5 * ones4

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [40]:
# Take the latest array to the power of 2 using '**'
r5 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [41]:
# Do the same thing with np.square()
np.square(r5)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [42]:
# Find the mean of the latest array using np.mean()
np.mean(r5)

3.8666666666666667

In [43]:
# Find the maximum of the latest array using np.max()
np.max(r5)

9

In [44]:
# Find the minimum of the latest array using np.min()
np.min(r5)

0

In [45]:
# Find the standard deviation of the latest array
np.std(r5)

2.578543947441829

In [46]:
# Find the variance of the latest array
np.var(r5)

6.648888888888889

In [47]:
# Reshape the latest array to (3, 5, 1)
r5.reshape((3, 5, 1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [48]:
# Transpose the latest array
r5.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [49]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
r6 = np.random.randint(10, size=(3, 3))
r7 = np.random.randint(10, size=(3, 2))

In [50]:
# Perform a dot product on the two newest arrays you created
r6.dot(r7)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [52]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
r8 = np.random.randint(10, size=(4, 3))
r9 = np.random.randint(10, size=(4, 3))

In [53]:
# Perform a dot product on the two newest arrays you created
r8.dot(r9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [54]:
r8.dot(r9.T)

array([[ 40,  36,  10,  12],
       [153, 111,  57,  60],
       [140, 100,  52,  56],
       [ 48,  30,  37,  18]])

In [55]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
r9.dot(r8.T)

array([[ 40, 153, 140,  48],
       [ 36, 111, 100,  30],
       [ 10,  57,  52,  37],
       [ 12,  60,  56,  18]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [56]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r10 = np.random.randint(10, size=(5, 3))
r11 = np.random.randint(10, size=(5, 3))

In [57]:
# Compare the two arrays with '>'
r10 > r11

array([[False,  True,  True],
       [ True,  True,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [58]:
# Compare the two arrays with '>='
r10 >= r11

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True, False, False],
       [False, False,  True]])

In [59]:
# Find which elements of the first array are greater than 7
r10 > 7

array([[False, False,  True],
       [False, False,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [60]:
# Which parts of each array are equal? (try using '==')
r10 == r11

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False,  True]])

In [61]:
# Sort one of the arrays you just created in ascending order
np.sort(r10)

array([[0, 4, 9],
       [6, 6, 8],
       [2, 9, 9],
       [0, 3, 6],
       [3, 4, 6]])

In [63]:
r10

array([[0, 4, 9],
       [6, 6, 8],
       [9, 9, 2],
       [6, 0, 3],
       [3, 4, 6]])

In [62]:
# Sort the indexes of one of the arrays you just created
np.argsort(r10)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [1, 2, 0],
       [0, 1, 2]])

In [64]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(r10)

2

In [65]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(r10)

0

In [66]:
r11

array([[6, 3, 6],
       [2, 5, 1],
       [9, 8, 4],
       [5, 3, 9],
       [6, 8, 6]])

In [67]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(r11, axis=1)

array([0, 1, 0, 2, 1])

In [68]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(r11, axis=0)

array([1, 0, 1])

In [69]:
# Create an array of normally distributed random numbers
np.random.normal(size=(5, 3))

array([[-0.2581848 ,  0.46095562, -1.34938997],
       [-1.01907279,  0.12701224, -1.24944372],
       [ 1.94511561, -0.15333646, -0.90698723],
       [-0.81735416, -0.48312268, -0.56982835],
       [-2.09159967,  1.26374053, -0.01548334]])

In [75]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, num=20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.